#!/usr/bin/env python3
import os

FILES = {}

FILES['backend/.env.example'] = r"""# Solana wallet keypair (base58 private key)
# This wallet needs devnet SOL for market creation transactions
# Get devnet SOL: https://faucet.solana.com
WALLET_KEYPAIR=your_base58_private_key_here

# Optional: comma-separated base58 keys for markets created by other wallets
# (e.g. markets created earlier with Phantom). Keeper picks the right key per market.
AUTHORITY_KEYPAIRS=

# AI keys
GROQ_API_KEY=your_groq_key_here
ELEVENLABS_API_KEY=your_elevenlabs_key_here
ELEVENLABS_VOICE_ID=your_voice_id_here

# TxLINE API token (generated by scripts/subscribe.js)
# Free World Cup tier — no payment needed
TXLINE_API_TOKEN=txoracle_api_...

# DO NOT commit .env to git — private keys live here
"""


def main():
    if not os.path.isdir("backend"):
        print("ERROR: run from kaching-settle repo root"); return
    for path, content in FILES.items():
        d = os.path.dirname(path)
        if d: os.makedirs(d, exist_ok=True)
        with open(path, "w") as f: f.write(content)
        print("wrote", path)
    print("Done. Run: git add backend/.env.example && git commit -m \'fix: add AUTHORITY_KEYPAIRS to .env.example\' && git push")


if __name__ == "__main__": main()
